# Generated by Django 2.0.5 on 2019-03-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='promotion',
            field=models.TextField(null=True),
        ),
    ]
