# Generated by Django 2.0.5 on 2019-04-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontpage', '0003_frontpage_promotion1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpage',
            name='image1',
            field=models.ImageField(null=True, upload_to='room/mycalendar'),
        ),
    ]
