# Generated by Django 2.0.5 on 2019-03-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bed_type', models.CharField(default='SOME STRING', max_length=50)),
                ('beds_number', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='room/')),
                ('weekday_price', models.PositiveIntegerField()),
                ('weekend_price', models.PositiveIntegerField()),
                ('promotion', models.TextField()),
                ('facility', models.TextField()),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Room',
            },
        ),
    ]
