# Generated by Django 2.0.5 on 2019-03-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('totalguest', models.PositiveIntegerField()),
                ('CheckIn', models.DateField()),
                ('CheckOut', models.DateField()),
                ('totalPrice', models.IntegerField(default=0)),
                ('notes', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.Room')),
            ],
            options={
                'verbose_name_plural': 'Reservation',
            },
        ),
    ]
