# Generated by Django 2.0.5 on 2019-03-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='weekday_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='weekend_price',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
