# Generated by Django 2.0.5 on 2019-03-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0003_auto_20190319_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='totalPrice',
        ),
    ]
