# Generated by Django 2.0.5 on 2019-03-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0004_remove_reservation_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
    ]
