# Generated by Django 2.0.5 on 2019-03-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0006_reservation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='TotalCost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nights',
            field=models.IntegerField(default=0),
        ),
    ]
