# Generated by Django 2.0.5 on 2019-03-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0007_auto_20190324_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='TotalCost',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nights',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
