# Generated by Django 2.0.5 on 2019-03-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0008_auto_20190324_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='totalguest',
        ),
        migrations.AddField(
            model_name='reservation',
            name='NumberOfGuest',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
