# Generated by Django 2.0.5 on 2019-04-14 22:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0011_auto_20190414_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=50, verbose_name='Summary')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_time', models.TimeField(default=datetime.time(7, 0), verbose_name='start_time')),
                ('end_time', models.TimeField(default=datetime.time(7, 0), verbose_name='end_time')),
                ('date', models.DateField(verbose_name='date')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Room.Room')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
