# Generated by Django 2.0.5 on 2019-04-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0015_auto_20190417_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='end_time',
        ),
    ]
