# Generated by Django 2.0.5 on 2019-04-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0016_remove_events_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='start_time',
            new_name='date_and_time',
        ),
    ]
