# Generated by Django 2.0.5 on 2019-04-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0017_auto_20190417_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='Event',
        ),
    ]
