# Generated by Django 2.0.5 on 2019-04-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0019_auto_20190419_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='CheckIn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='CheckOut',
            field=models.DateTimeField(),
        ),
    ]
