# Generated by Django 2.0.5 on 2019-04-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0020_auto_20190419_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='summary',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1),
        ),
    ]
