# Generated by Django 2.0.5 on 2019-04-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0021_auto_20190420_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='summary',
            field=models.CharField(choices=[('!', '!'), ('@', '@'), ('#', '#'), ('$', '$')], max_length=1),
        ),
    ]
