# Generated by Django 2.0.5 on 2019-04-19 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0022_auto_20190420_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='created_at',
        ),
    ]
